try:
    while True:
        continue
except Exception as e:
    print(e)
